<?php
/**
 * File containing the MKVMergeCommand class
 *
 * @version $Id$
 * @copyright 2010
 */

/**
 * This class allows manipulation of a mkvmerge command generated by the GUI
 */
class MKVMergeCommand
{
	/**
	 * Constructor
	 *
	 * @param string $command A mkvmerge command generated from the GUI
	 * @param string $targetDisk A mkvmerge command generated from the GUI
	 */
	function __construct( $command )
	{
		$this->command = $command;
		$this->_extractType();
		$this->_extractFiles();

	}

	protected function _extractFiles()
	{
		if ( $this->conversionType == 'movie' )
		{
			// parse the command to get the target / sources
			if ( !preg_match( '#/media/storage/[^/]+/Movies/([^/]+)/\1\.(avi|mkv)#', $this->command, $matches ) )
				throw new Exception("Unable to identify the target in the transformed command" );
			$this->title = $matches[1];
			$this->target = dirname( $matches[0] );
			$this->linkTarget = "/media/aggregateshares/Movies/";
		}
		elseif ( $this->conversionType == 'tvshow' )
		{
			// parse the command to get the target / sources
			if ( !preg_match( '#/media/storage/[^/]+/TV Shows/([^/]+)/([^/]+)\.(avi|mkv)#', $this->command, $matches ) )
				throw new Exception("Unable to identify the target in the transformed command" );
			$this->showName = $matches[1];
			$this->episodeName = $matches[2];
			$this->title = $episodeName;
			$this->target = $matches[0];
			$this->linkTarget = "/media/aggregateshares/$type/$showName/";
		}
	}

	/**
	 * Analyzes the command and stores the conversion type (movie / tvshow)
	 * in self::$type
	 */
	protected function _extractType()
	{
		if ( strstr( $this->command, '/complete/Movies/' ) !== false )
		{
			$this->conversionType = 'movie';
		}
		elseif ( strstr( $this->command, '/complete/TV/' ) !== false )
		{
			$this->conversionType = 'tvshow';
		}
		else
			throw new Exception( "Unable to extract the conversion type" );
	}

	/**
	 * The final command, after conversion
	 * @var string
	 */
	public $command;

	/**
	 * Conversion type: movie/tvshow
	 */
	public $conversionType;

	/**
	 * The conversion title, either the movie name, or the tv show name + episode
	 * @var string
	 */
	public $title;

	/**
	/**
	 * The conversion target folder
	 * @var string
	 */
	public $target;

	/**
	 * The TV Show name. Only set for $type == tvshow
	 * @var string
	 */
	public $showName;

	/**
	 * The TV Show episode name. Only set for $type == tvshow
	 * @var string
	 */
	public $episodeName;

	/**
	 * The target to be used as the symbolic link
	 * @var string
	 */
	public $linkTarget;
}
?>