<?php

// File automatically generated by PHPEdit
// PHPEdit's unit tests extension might not work as expected if you modify this file

require_once 'PHPUnit/Util/Filter.php';

PHPUnit_Util_Filter::addFileToFilter(__FILE__);

if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'lib_mkvmerge_AllTests::main');
    chdir(dirname(dirname(__FILE__)));
}

require_once 'PHPUnit/Framework/TestSuite.php';
require_once 'PHPUnit/TextUI/TestRunner.php';

// PHPEdit Inclusions -- dot not remove this comment
require_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'commandTest.php';
require_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'commandimportwindowsguiTest.php';
require_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'commandqueueTest.php';
// /PHPEdit Inclusions -- dot not remove this comment

class lib_mkvmerge_AllTests
{
    public static function main()
    {
        PHPUnit_TextUI_TestRunner::run(self::suite());
    }

    public static function suite()
    {
        $suite = new PHPUnit_Framework_TestSuite('PHPUnit_Framework');

		// PHPEdit Tests suites -- dot not remove this comment
		$suite->addTestSuite('MKVMergeCommandTest');
		$suite->addTestSuite('MKVMergeCommandImportWindowsGUITest');
    	$suite->addTestSuite('MKVMergeCommandQueueTest');
    	// /PHPEdit Tests suites -- dot not remove this comment

        return $suite;
    }
}

if (PHPUnit_MAIN_METHOD == 'lib_mkvmerge_AllTests::main') {
    lib_mkvmerge_AllTests::main();
}
?>
